# Rendimiento
org.gradle.jvmargs=-Xmx2G -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Versiones
minecraft_version=1.20.1
loader_version=0.15.11
loom_version=1.6.5

# Propiedades del mod
mod_version=1.2.0
maven_group=com.tontoque28
archives_base_name=tinyfarmbossaddon

# API estable
fabric_api_version=0.92.0+1.20.1